### ISSUE TITLE
Consider shorthand for specifying versions

### ISSUE THREAD

**Issue by DanielKeep** [withoutboats/cargo-add#1]
It would be convenient to list dependency versions the same way [`cargo script`](https://github.com/DanielKeep/cargo-script) does.  It allows a `name=ver` shorthand, like `toml=0.1.20`.  This would _also_ allow users to specify multiple specifically-versioned dependencies in a single command.

**Comment by withoutboats** [comment]
I'll look into that. I tried to allow multiple dependencies of any kind, but docopts couldn't disambiguate the flags from dependencies (which is valid I think, afaik nothing stops someone from creating a crate called --version, for example). The equal syntax could solve that though.

**Comment by withoutboats** [comment]
Actually, the = syntax is rather ugly with many kinds of semver (e.g. "toml=>=0.1"). A version not tagged to a particular version isn't likely input for your script running tool, but it is for a tool like cargo add.

**Comment by DanielKeep** [comment]
Personally, I always just use the default constraint (_i.e._ the implicit `^`) as the lowest "known-good" version.  My experience has been either that's what you want, or you just don't care (and use `*`).  You _could_ allow only nothing (implicit `*`) or a version number (implicit `^`).

_Alternately_, you could just advise people to quote the version, which doesn't look _as_ bad: `toml='>=0.1'`.

**Comment by withoutboats** [comment]
It seems docopts can't take optional version arguments (e.g. <dep>[=<version>]) because it will read the equal sign as a part of the <dep> argument. Closing this for now.
